user:
  github:
    clientId: c3c514279462548fdf61
    clientSecret: 76a2bb4074731d9d4856ec952832512564aa471a
    tokenUri: https://github.com/login/oauth/access_token
    redirectUri: http://localhost:8080/github/thirdLoginCallBack
    userInfoUrl: https://api.github.com/user
  google:
    clientId: 918272533109-mq26hm62t2vb7ommrh9t5qtu24n1jusm.apps.googleusercontent.com
    clientSecret: Yy57lgdCs36kMlk4mg4IaS14
    redirectUrl: http://localhost:8080/google/thirdLoginCallBack
    tokenUrl: https://oauth2.googleapis.com/token
    grantType: authorization_code
    userInfoUrl: https://www.googleapis.com/oauth2/v1/userinfo



server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/